# Apostraphe Guidelines ::
## Remember to precede them with a YAML escape character ('), a single apostraphe.

dates:
  # January
  '01-01':
    title: 'Days of January 1st Past: Bell Labs (1925), Hewlett-Packard (1939), and Agner K. Erlang (1878)'
    description: 'On January 1, 1925, Bell Telephone Laboratories, Inc. was organized to consolidate the development and research activities in the communication field and allied sciences for the Bell System.'
    bash_script: ''

  '01-03':
    title: 'Days of January 3rd Past: The Bitcoin Genesis Block'
    description: "Bitcoin's genesis block contains the now-famous message: 'The Times 03/Jan/2009 Chancellor on brink of second bailout for banks.' This message references the deteriorating financial conditions of that time and the rationale for creating Bitcoin."
    bash_script: ''

  '01-04':
    title: 'Days of January 4th Past: Isaac Newton (1643)'
    description: ''
    bash_script: ''

  '01-09':
    title: 'Days of January 9th Past: The iPhone (2007)'
    description: 'On this day, Steve Jobs announced the 1st iPhone at Macworld (2007) in San Francisco.'
    bash_script: ''

  '01-15':
    title: 'Days of January 15th Past: Jimmy Wales and Larry Sanger Introduce Wikipedia (2001)'
    description: ''
    bash_script: ''

  '01-16':
    title: 'Days of January 16th Past: Netflix Introduces Streaming (2007)'
    description: ''
    bash_script: ''

  '01-17':
    title: 'Days of January 17th Past: Benjamin Franklin (1706) and Muhammad Ali (1942)'
    description: "Float like a butterfly, sting like a bee; the hands can't hit what the eyes can't see. - Muhammad Ali"
    bash_script: 'january/muhammad-ali-birthday.sh'

  '01-18':
    title: 'Days of January 18th Past: Colossus Mark 1 is Delivered to Bletchley Park (1944)'
    description: ''
    bash_script: ''

  '01-20':
    title: 'Days of January 20th Past: Eisenhower (1953), Obama (2009), and DynamoDB (2012)'
    description: ''
    bash_script: 'january/obama-inauguration-day.sh'

  # Barack Obama is sworn in as the 44th President of the United States of America (2009)
  # Amazon DynamoDB was released by Werner Vogels (CTO at Amazon) on January 18, 2012.

  '01-31':
    title: 'Days of January 31st Past: Luis Suárez Joins Liverpool FC (2011)'
    description: ''
    bash_script: ''

  # February
  '02-04':
    title: 'Days of February 4th Past: Facebook (2004)'
    description: ''
    bash_script: ''

  '02-11':
    title: 'Days of February 11th Past: Thomas Edison (1847)'
    description: ''
    bash_script: ''

  '02-14':
    title: 'Days of February 14th Past: Navstar II-1 (1989) and YouTube (2005)'
    description: 'Steve Checn, Chad Hurley, and Jawed Karim founded YouTube on this day in 2005.'
    bash_script: ''

  '02-22':
    title: 'Days of February 22nd Past: Miracle on Ice (1980)'
    description: ''
    bash_script: ''

  # March
  '03-14':
    title: 'Days of March 14th Past: SpaceX (2002)'
    description: ''
    bash_script: ''

  '03-15':
    title: 'Days of March 15th Past: Julius Caesar and the Ides of March (44 BC)'
    description: ''
    bash_script: ''

  '03-30':
    title: 'Days of March 30th Past: Vincent van Gogh (1853)'
    description: ''
    bash_script: ''

  '03-31':
    title: 'Days of March 31st Past: Johann Sebastian Bach (1685)'
    description: ''
    bash_script: ''

  # April
  '04-01':
    title: 'Days of April 1st Past: Otto von Bismark (1815) and Apple Computer, Inc. (1976)'
    description: 'Steve Jobs, Steve Wozniak, and Ronald Wayne founded Apple on this day in 1976.'
    bash_script: ''

  '04-04':
    title: 'Days of April 4th Past: Microsoft (1975)'
    description: 'Bill Gates and Paul Allen founded Microsoft on this day in 1975.'
    bash_script: ''

  '04-07':
    title: 'Days of April 7th Past: Bob Metcalfe (1946)'
    description: ''
    bash_script: ''

  '04-23':
    title: 'Days of April 23rd Past: William Shakespeare (1564)'
    description: ''
    bash_script: ''

  '04-26':
    title: 'Days of April 26th Past: Marcus Aurelius (121 AD)'
    description: ''
    bash_script: ''

  '04-28':
    title: 'Days of April 28th Past: Kurt Gödel (1906)'
    description: ''
    bash_script: ''

  '04-29':
    title: 'Days of April 29th Past: Paul Baran (1926) and CERN (1954)'
    description: "Paul Baran, computer technologist and entrepreneur was responsible for one of the fundamental concepts that enable today's advanced computer networking systems: digital packet-switching."
    bash_script: ''

  '04-30':
    title: 'Days of April 30th Past: Claude Shannon (1916)'
    description: 'Today we celebrate Claude Shannon (1916-2001), the father of information theory.'
    bash_script: ''

  # May
  '05-05':
    title: 'Days of May 5th Past: Gladiator (2000)'
    description: ''
    bash_script: ''

  '05-07':
    title: 'Days of May 7th Past: Liverpool vs. Barcelona (2019)'
    description: ''
    bash_script: ''

  '05-11':
    title: 'Days of May 11th Past: Richard Feynman (1918)'
    description: 'Celebrating the life of Richard Feynman (1918-1988), renowned physicist and educator.'
    bash_script: ''

  '05-15':
    title: 'Days of May 15th Past: Shrek 2 (2004)'
    description: 'Shrek 2 (2004) Premiers at Cannes Film Festival'
    bash_script: ''

  '05-17':
    title: 'Days of May 17th Past: Alan Kay (1940) and Random Access Memories (2013)'
    description: ''
    bash_script: ''

  '05-22':
    title: 'Days of May 22nd Past: Ethernet (1973)'
    description: ''
    bash_script: ''

  '05-25':
    title: 'Days of May 25th Past: The Miracle of Istanbul (2005)'
    description: ''
    bash_script: ''

  '06-08':
    title: 'Days of June 8th Past: Tim Berners-Lee (1955)'
    description: ''
    bash_script: ''

  # June
  '06-11':
    title: 'Days of June 11th Past: Michael Jordan (1997)'
    description: ''
    bash_script: ''

  '06-16':
    title: 'Days of June 16th Past: IBM (1911)'
    description: ''
    bash_script: ''

  '06-17':
    title: 'Days of June 17th Past: M.C. Escher (1898)'
    description: ''
    bash_script: ''

  '06-21':
    title: 'June (Summer) Solstice'
    description: ''
    bash_script: ''

  '06-23':
    title: 'Days of June 23rd Past: Alan Turing (1912) and Vint Cerf (1943)'
    description: 'Honoring Alan Turing (1912-1954), pioneer of computer science and artificial intelligence.'
    bash_script: ''

  '06-26':
    title: "Days of June 26th Past: Harry Potter and the Sorcerer's Stone (1997)"
    description: ''
    bash_script: ''

  '06-28':
    title: 'Days of June 28th Past: Gavrilo Princip (1914)'
    description: 'On this fateful day in 1914, Gavrilo Princip assassinated Archduke Franz Ferdinand of Austria-Hungary.'
    bash_script: ''

  '06-29':
    title: 'Days of June 29th Past: React (2013)'
    description: 'On this day, Facebook (Meta) open-sourced React at JS Conf 2013.'
    bash_script: ''

  '06-30':
    title: 'Days of June 30th Past: Thomas Sowell (1930)'
    description: ''
    bash_script: ''

  # July
  '07-01':
    title: 'Days of July 1st Past: Gottfried W. Leibniz (1646) and Xerox PARC (1970)'
    description: ''
    bash_script: ''

  '07-04':
    title: 'Happy Fourth of July!'
    description: 'Celebrating Independence Day in the United States.'
    bash_script: ''

  '07-05':
    title: 'Days of July 5th Past: Amazon (1994)'
    description: 'Jeff Bezos founded Amazon on this day in 1994.'
    bash_script: ''

  '07-08':
    title: 'Days of July 8th Past: John D. Rockefeller (1839)'
    description: ''
    bash_script: ''

  '07-09':
    title: 'Days of July 9th Past: Marc Andreessen (1971)'
    description: ''
    bash_script: ''

  '07-10':
    title: 'Days of July 10th Past: Nikola Tesla (1856)'
    description: ''
    bash_script: ''

  '07-15':
    title: 'Days of July 15th Past: Rembrandt (1606)'
    description: ''
    bash_script: ''

  '07-20':
    title: 'Days of July 20th Past: Alexander the Great (356 BC)'
    description: ''
    bash_script: ''

  '07-29':
    title: 'Days of July 29th Past: The Fellowship of the Ring (1954)'
    description: 'On this day in 1954, J.R.R. Tolkien published The Lord of the Rings: The Fellowship of the Ring.'
    bash_script: ''

  # August
  '08-15':
    title: 'Days of August 15th Past: Napoleon (1769)'
    description: 'Napoleon Bonaparte, French emperor and military general, was born today on the island of Corsica in 1769.'
    bash_script: ''

  '08-16':
    title: 'Days of August 16th Past: The First Transatlantic Telegraph Message (1858)'
    description: 'Europe and America are united by telegraphic communication. Glory to God in the highest, on earth peace, goodwill to men.'
    bash_script: ''

  # September
  '09-02':
    title: 'Days of September 2nd Past: Google Chrome (2008)'
    description: ''
    bash_script: ''

  '09-04':
    title: 'Days of September 4th Past: Google, Inc. (1998)'
    description: 'On this day in 1998, Larry Page and Sergey Brin founded Google, Inc.'
    bash_script: ''

  '09-14':
    title: 'Days of September 14th Past: Human Action (1949)'
    description: 'On this day in 1949, Ludwig von Mises published Human Action: A Treatise on Economics'
    bash_script: ''

  '09-18':
    title: 'Days of September 18th Past: Rush Hour (1998)'
    description: ''
    bash_script: ''

  '09-22':
    title: 'Days of September 22nd Past: Robert Lewandowski (2015)'
    description: 'On this day in 2015, Polish Striker, Robert Lewandowski scored 5 goals in 9 minutes for Bayern Munich in a Bundesliga match against Wolfsburg.'
    bash_script: ''

  '09-24':
    title: 'Days of September 24th Past: Superforecasting (2015)'
    description: ''
    bash_script: ''

  '09-28':
    title: 'Days of September 28th Past: Pokemon Red and Blue (1998)'
    description: ''
    bash_script: ''

  '09-29':
    title: 'Days of September 29th Past: Enrico Fermi (1901)'
    description: ''
    bash_script: ''

  # October
  '10-04':
    title: 'Days of October 4th Past: Sputnik 1 (1957)'
    description: "On this day in 1957, the Soviet Union launched the world's first artificial satellite, Sputnik 1."
    bash_script: ''

  '10-05':
    title: 'Days of October 5th Past: Sidney Crosby (2005)'
    description: ''
    bash_script: ''

  '10-15':
    title: 'Days of October 15th Past: UNIX (1973)'
    description: 'On this day, Ken Thompson and Dennis Ritchie presented the UNIX operating system at the 1973 Symposium on Operating Systems Principles.'
    bash_script: ''

  '10-16':
    title: 'Days of October 16th Past: Disney (1923), Skunk Works (1943), and The Lion, the Witch and the Wardrobe (1950)'
    description: ''
    bash_script: ''

  '10-29':
    title: 'Days of October 29th Past: The First ARPANET Message (1969)'
    description: "On this day, UCLA computer science student, Charley Kline, sent the first ARPANET message ('LO') to the Stanford Research Institute's computer in Menlo Park, California."
    bash_script: ''

  '10-31':
    title: 'Days of October 31st Past: 95 Theses (1517)'
    description: 'On this day, Martin Luther nailed his 95 Theses to the church door in Wittenberg, Germany, an act that sparked the Protestant Reformation and changed the course of religious history.'
    bash_script: ''

  # November
  '11-02':
    title: 'Days of November 2nd Past: George Boole (1815)'
    description: ''
    bash_script: ''

  '11-27':
    title: 'Days of November 27th Past: Bruce Lee (1940)'
    description: 'On this day, Bruce Lee - actor, martial artist, and cultural icon - was born.'
    bash_script: ''

  # December
  '12-07':
    title: 'Days of December 7th Past: Pearl Harbor (1941)'
    description: 'A date which will live in infamy.'
    bash_script: ''

  '12-21':
    title: 'December (Winter) Solstice'
    description: ''
    bash_script: ''

  '12-25':
    title: '🎄 Merry Christmas!'
    description: 'Merry Christmas to all, and to all a good night.'
    bash_script: ''

  '12-28':
    title: 'Days of December 28th Past: John von Neumann (1903) and Linus Torvalds (1969)'
    description: ''
    bash_script: ''

  '12-31':
    title: 'Days of December 31st Past: MIT Radiation Laboratory (1945)'
    description: ''
    bash_script: ''
